### ISSUE TITLE
Can't type numbers in ip address string

### ISSUE THREAD

**Issue by stepik** [XITRIX/Moonlight-Switch#10]
Can't type numbers in ip address string they are gray. And some games and desktop screen very often don't switch to 1280x720 resolution.

**Comment by XITRIX** [comment]
Yes, for unknown reasons, sometimes, keyboard changes it’s layout, just restart an app, it should fix the keyboard.
Changing resolution is not an issue of moonlight, it’s an issue (or a feature) of nvidia shield service.

**Comment by XITRIX** [comment]
I've found the problem and fixed it, here is the fixed build:

[br_moonlight.nro.zip](https://github.com/XITRIX/Moonlight-Switch/files/7079540/br_moonlight.nro.zip)

I'll close that issue when it will be included in final release.

**Comment by XITRIX** [comment]
I've found the problem and fixed it.

Fixed in Release v0.7.1.

**Comment by sucaiji** [comment]
This problem still alive in v0.8.    switch version v11.0.0

**Comment by XITRIX** [comment]
Attach a screenshot plz

**Comment by XITRIX** [comment]
I'll close this issue, cause I cannot reproduce it.
Feel free to reopen it, if you are sure that it was not fixed.
