### ISSUE TITLE
Can not run app

### ISSUE THREAD

**Issue by linhtranvu** [XITRIX/Moonlight-Switch#11]
I am using moonlight-nx and decide give this app a try. I clear all moonlight folder, install nro into  new moonlight folder. I can add host, but when start streaming I got error: app enter error and quit
Os: 12.1.0
Atmosphere: 0.9.4
I guess you need to recompile nro for newest os version to work.

**Comment by renA21** [comment]
Works fine on latest HOS version. The problem is most likely that you're not running latest Atmosphere since the version you're using is old.

**Comment by linhtranvu** [comment]
I make a clean installation with atmosphere 20.1, now work perfectly 

Will test more and feedback about stability
