### ISSUE TITLE
LAlt key not acting as LAlt should

### ISSUE THREAD

**Issue by TheRealPepsi** [XITRIX/Moonlight-Switch#114]
### Describe the bug

Title pretty much says it all, the alt key on the on screen keyboard seems to act differently to LAlt, perhaps Altgr, but altf4 doesn't work, alt+enter doesn't work, and alt+tab acts more like altgr+tab, with it not disappearing upon altkey release, having to click on a tab, rather than cycle to it with tab. 

### To reproduce

1. Enter virtual mouse mode
2. Press X for keyboard
3. Press the altkey on the left, and try f4, enter, and tab

### Expected behavior

F4 should close the app, enter should go fullscreen on supported apps, tab should act as described in report

### Operating system

16.1.0, AMS

**Comment by XITRIX** [comment]
I'm pretty sure that it works as left Alt, cause I used alt+f4 a lot, but I'll check.

Did you noticed that tapping on alt works like trigger? (You need to tap it again to release the button) I've made it to make combinations like alt+f4 easier to perform with one hand. So you need to tap alt -> f4 -> alt again.

Btw I'll check later when I'll have an access to my Switch

**Comment by TheRealPepsi** [comment]
I did notice, and it's still the same problem, but I found what the cause of it is. When I switched my keyboard layout to US (was on UK) It worked fine then!

**Comment by XITRIX** [comment]
Then I think I cannot “fix” it, cause it is not really a bug. Moonlight has no idea about layout of keyboard selected on PC, and just sends the keycodes related to the layout selected in Moonlight itself, so if layouts on Moonlight and PC does not match, issues like that could happen
