### ISSUE TITLE
An error occurs when exiting

### ISSUE THREAD

**Issue by GuoDongG** [XITRIX/Moonlight-Switch#119]
### Describe the bug

when i quit the moonlight,it always got an error.

### To reproduce

1. Go to moonlight-switch
2. play or setting something
3. Tap on b to quit it

### Expected behavior

No more crashes

### Screenshots

![9629D15E3A7D68457E477685F6396E2B](https://github.com/XITRIX/Moonlight-Switch/assets/75298254/000ff707-5e16-41fd-a09c-913e43ed56b2)

### Operating system

16.0.3|AMS 1.5.4|E

**Comment by sebbe1985** [comment]
I'm having exactly the same problem on 2 different switches

**Comment by XITRIX** [comment]
Applet mode is not supported, use Title redirection please
