### ISSUE TITLE
When Y is pressed, guide button is pressed as well

### ISSUE THREAD

**Issue by lucascanero** [XITRIX/Moonlight-Switch#120]
### Describe the bug

Iam actually running sunshine on my host machine. When I connect my switch to the host and go to a controller tester, and the button Y is being pressed, the guide button is pressed as well. Everytime I press Y, the steam overlay show up pausing everything. It is very annoying

### To reproduce

1. Connect to the host
2. Check any gamepad tester

### Screenshots

![IMG_0947](https://github.com/XITRIX/Moonlight-Switch/assets/54242962/64dbf157-d22d-4ffc-b17c-55c7d68055cd)

### Operating system

Switch

**Comment by XITRIX** [comment]
Should be fixed in [v0.13.4](https://github.com/XITRIX/Moonlight-Switch/releases/tag/v0.13.4)
