### ISSUE TITLE
Stream is not smooth until going into moonlight overlay

### ISSUE THREAD

**Issue by GHYAKIMA** [XITRIX/Moonlight-Switch#121]
### Describe the bug

Using different sunshine/moonlight configuration does not fix this issue
The ""overlay workaround" is not **permanent fix**. Stream starts to stutter after a while.

### Screenshots

https://github.com/XITRIX/Moonlight-Switch/assets/36603223/ff90e076-5ed6-469e-82bf-74109f9032dc

### Operating system

16.1.0|AMS 1.5.5|E

**Comment by rafraleo** [comment]
What is this overlay workaround? Just installed moonlight on switch and the stream is really laggy. Like it’s ins 30fps but everything is set up to 60fps

**Comment by XITRIX** [comment]
Should be fixed in v1.0
