### ISSUE TITLE
Playstation Controllers Button Assignment using Sunshine

### ISSUE THREAD

**Issue by Clubdidu** [XITRIX/Moonlight-Switch#122]
### Describe the bug

Using Sunshine and setting DS4 controller for playstation button layout works. However pushing on the joy-cons (X) -> Triangle works, but it at the same time assigned to push the "touchpad" click. Is it possible to assign the touchpad click to the "-" button of the joy-cons? For example to use Maps in Games. Using the Xbox Layout in Sunshine works flawlessly, its just preferring the playstation layout.

Thanks

![Screenshot 2023-11-10 101245](https://github.com/XITRIX/Moonlight-Switch/assets/65295513/680689ac-b3b9-43d2-bcf0-28c233654b54)

### To reproduce

1. Go to 'Sunshine, put DS4 Controller'
2. Tap on '....'

**Comment by XITRIX** [comment]
Was fixed on Moonlight-Common-C side
