### ISSUE TITLE
"Error - Timeout was reached" can only be closed with the touch screen

### ISSUE THREAD

**Issue by miberk90** [XITRIX/Moonlight-Switch#124]
### Describe the bug

Whenever I'm streaming and I quit the application (with moonlight overlay), I'll get an error message saying "Error - Timeout was reached". The only way to close it is by using the touch screen, controllers can't hit the "close" button. So when I am docked, the error stays on the screen until I either quit Moonlight or I undock it, tap "close", then redock it.

### To reproduce

1. Start stream
2. Close stream by hitting + and -, then clicking Terminate App
3. Hit - again to terminate app
4. Get error message

### Expected behavior

just quit game without the error message

**Comment by XITRIX** [comment]
Should be fixed in latest release, feel free to reopen if issue still presented
