### ISSUE TITLE
Joycon Vibration Amplifier Configuration

### ISSUE THREAD

**Issue by TavinTS** [XITRIX/Moonlight-Switch#125]
### Is your feature request related to a problem? Please describe.

Unfortunately, at least when streaming with Sunshine as host and Switch as client, the joycon's vibration is really weak, you can barely feel it.

### Describe the solution you'd like

The best solution would be to have an option to increase / amplify vibration intensity on joycons.

Many thanks for the attention!

**Comment by XITRIX** [comment]
Vibration rates was improved, now should works fine

If improvements still needed, please, reopen this issue
