### ISSUE TITLE
Mouse passthrough not working.

### ISSUE THREAD

**Issue by VGT789** [XITRIX/Moonlight-Switch#128]
### Describe the bug

When I plug a mouse by USB-c on switch/docked switch the passthrough doesn't work i.e. no tracking and none of the mouse buttons work.

### To reproduce

Plug a mouse to the console by using an adapter or the dock.

### Operating system

17.0.0|AMS 1.6.2|E v0.1.3.4

### Additional context

Tested using the same adapter on an android phone and it works fine.
Right now i don't have another mouse to test if the problem is caused by this specific mouse.

**Comment by hongzhizhou** [comment]
I used the type-c cable to connect the mouse and it could work fine, but the delay was very high. The mouse I used was Logitech G703.

**Comment by XITRIX** [comment]
Cannot replicate, mouse works for me
