### ISSUE TITLE
Пишет что ПК не сопряжён 

### ISSUE THREAD

**Issue by Slavik2301** [XITRIX/Moonlight-Switch#130]
### Describe the bug

На телефоне и на нинтендо свитч при вводе кода на ПК для сопряжения устройств либо ничего не происходит либо пишет ПК не сопряжён!
Драйвера последние обновления!
![SAVE_20240104_131129](https://github.com/XITRIX/Moonlight-Switch/assets/155629003/71dbb7db-d43e-47a2-8c87-c3b77cab7529)

### To reproduce

2. Tap on '....'

**Comment by XITRIX** [comment]
Это не проблема Switch клиента, по этому вопрос немного не по адресу. Советую обратиться за помощью на [официальном Discord канале Moonlight](https://discord.gg/fmtcVPzaG4) в канале из раздела "Moonlight Hosts" в зависимости от того, какой клиент используется у вас на компьютере
