### ISSUE TITLE
D-Pad has bug

### ISSUE THREAD

**Issue by Lyaksa** [XITRIX/Moonlight-Switch#131]
### Describe the bug

![Uploading IMG_3450.jpeg…]()

D-Pad has bug.When I am playing Re4, it will automatically switch weapons. D-Pad is used to switch weapons. I've already tried to replace a joy-con，but the issue remains. So I think the problem comes from here. This bug has been bothering me for a long time. Can it be fixed? Thank you.

### To reproduce

2. Tap on '....'

**Comment by XITRIX** [comment]
Not enough information to reproduce the issue. If problem still presented, please, provide more details about it
