### ISSUE TITLE
[Feature] Onscreen guide button

### ISSUE THREAD

**Issue by GrayXu** [XITRIX/Moonlight-Switch#132]
### Describe the bug

Changed multiple different key combinations, still unable to use the guide key.

### Expected behavior

By using the configured guide key buttons combination, you can trigger the guide key and open layers like Steam overlay

### Operating system

v0.13.4 + AMS v1.6.2

**Comment by XITRIX** [comment]
Try to check if it works with iOS/Android versions of Moonlight first, potentially it's your PC setting issue

**Comment by GrayXu** [comment]
Thank you for your reply! I have turned off Xbox overlay and tried using iOS Moonlight with DualShock 4, and I can open Steam overlay normally. However, in Moonlight-Switch, I still cannot open Steam overlay with the combination keys. But opening the Moonlight-Switch overlay is normal.  
However, this bug does not significantly affect the specific gaming streaming experience.

**Comment by XITRIX** [comment]
Ok, I'll try to figure it out, why guide button not work, to be honest I had a lot of problems with it

**Comment by XITRIX** [comment]
Checked it yesterday, it works. Default "-" + "R" combination is not great, because it cause "Guide + R = Screenshot" in steam, but still, it works

**Comment by imkrut** [comment]
> Checked it yesterday, it works. Default "-" + "R" combination is not great, because it cause "Guide + R = Screenshot" in steam, but still, it works

Any chance to map Guide + other buttons to other keyboard keys?

**Comment by XITRIX** [comment]
What do you mean? Which keyboard? If you are talking about gamepad key combination, you could change it in app's settings

**Comment by GrayXu** [comment]
> Checked it yesterday, it works. Default "-" + "R" combination is not great, because it cause "Guide + R = Screenshot" in steam, but still, it works

I tried using the "-" + "R" combination and it did work. But using something like "-" + "X" combination is ineffective.

**Comment by XITRIX** [comment]
I think it could just interfere with some system combos from Windows (Guide + X) and because of that you cannot see button's effect, but true, current way of using combos for Guide is not the best way to do, maybe I should implement onscreen button in one of the screen corners

**Comment by XITRIX** [comment]
As soon as option to override system button to Guide was implemented, onscreen Guide button is not planned anymore.
Maybe I will reopen it later for iOS or other platform
