### ISSUE TITLE
Semi transparent gray box on the lower right

### ISSUE THREAD

**Issue by orangpelupa** [XITRIX/Moonlight-Switch#133]
### Describe the bug

There's a useless grey semitransparent box on the lower right. Only appear when streaming. Also appear on the server

### To reproduce

1. Stream desktop 

### Expected behavior

No gray box

### Screenshots

![Screenshot_2024-01-28-18-29-49-183_com google android apps photos-edit](https://github.com/XITRIX/Moonlight-Switch/assets/16116746/823919c0-f544-4d45-8e49-348d22957ac2)

### Operating system

16.1.0|AMS 1.5.5|E

**Comment by orangpelupa** [comment]
The Workaround is by killing the sunshine svc via task manager, then run sunshine again.
Thej if lucky, no grey box when streaming

**Comment by XITRIX** [comment]
Moonlight-Switch has nothing to do with this grey box, it's not client related

I could suggest you to ask help in discord in Sunshine channel
