### ISSUE TITLE
[Feature] Block app with description message on launch using Applet Mode

### ISSUE THREAD

**Issue by thinhvnn** [XITRIX/Moonlight-Switch#134]
### Describe the bug

I tested 2 modes: applet mode vs non applet mode. The results show that applet mode has much better performance.
Take a look at the picture of ram usage and cpu usage in applet mode.

### To reproduce

2. Tap on '....'

### Screenshots

![2024020519431100](https://github.com/XITRIX/Moonlight-Switch/assets/159027988/64ed3b71-bc32-42ef-bef1-d2463ebb293d)
![2024020519433400](https://github.com/XITRIX/Moonlight-Switch/assets/159027988/f93380fe-2e31-4e18-895f-78fa9c9dd5bc)

**Comment by XITRIX** [comment]
Maybe it's not clear enough but in [Installing](https://github.com/XITRIX/Moonlight-Switch?tab=readme-ov-file#installing) section of ReadMe, 3rd step tells you that you SHOULD launch an app using Title Redirection (non applet mode)

To be honest I'm shocked that launching this app in applet mode didn't crashed your Atmosphere. For sure I'll add blocker screen for trying to open app in applet mode.

**Comment by thinhvnn** [comment]
Iam sorry. 

> Maybe it's not clear enough but in [Installing](https://github.com/XITRIX/Moonlight-Switch?tab=readme-ov-file#installing) section of ReadMe, 3rd step tells you that you SHOULD launch an app using Title Redirection (non applet mode)
> 
> To be honest I'm shocked that launching this app in applet mode didn't crashed your Atmosphere. For sure I'll add blocker screen for trying to open app in applet mode.

Iam sorry. My mistake, I wrote it wrong. What I mean is that running in applet mode gives better performance than non applet mode. CPU usage in applet mode is less resource intensive than non-applet mode. Please try it

**Comment by XITRIX** [comment]
Hmm... Ok, I'll check

**Comment by XITRIX** [comment]
![IMG_5741](https://github.com/XITRIX/Moonlight-Switch/assets/9553519/4ab7016c-9cf5-4033-bc6f-4c4b3de4d820)

I have no idea how you make it work in Applet Mode to be honest

**Comment by thinhvnn** [comment]
This is my system:
![system](https://github.com/XITRIX/Moonlight-Switch/assets/159027988/d9bd0918-da2f-4f97-ab76-736415826548)
It also frequently crashes in applet mode. You can try several times.
This is the result when in applet mode. You can see the cpu is only used about 60%, Ram is only used about 600mb:
![applet](https://github.com/XITRIX/Moonlight-Switch/assets/159027988/58123302-bd78-48cc-8946-b7c2ef0018a7)
This is the result in non-applet mode. CPU usage over 90%. Ram uses about 3 GB, this is non-applet mode. You may see a "Bad connection" message at the bottom of the screen:
[
![non-applet](https://github.com/XITRIX/Moonlight-Switch/assets/159027988/49664059-f767-4f33-accf-41cfc9caa937)
](url)

**Comment by XITRIX** [comment]
You can see low resource usage because Applet Mode do not allow app to get more, when I tried, my stream worked for a second and then freeze completely with crashing Atmosphere over time.

**Comment by thinhvnn** [comment]
It's so strange. When I stream successfully, it won't crash while streaming. Same bitrate 25000 at 1080p, applet mode makes cpu run well at default 1020mhz, non-applet cannot run well

**Comment by XITRIX** [comment]
I can add it, but I see no reason for it, dock is not able to output more than 1080p, so why torment Switch's hardware to decode 4k just to downscale image to 1080p, if you could downscale it on Host side

**Comment by XITRIX** [comment]
Implemented in v1.0
