### ISSUE TITLE
 The mouse pointer is not working properly 

### ISSUE THREAD

**Issue by gfds2005** [XITRIX/Moonlight-Switch#136]
When I use version 1.0.0 streaming, the mouse pointer is always forced to move to the upper left of the screen, making it untouchable.And version 0.13.4 looks fine.

**Comment by ShinRaikdou** [comment]
Same issue.

**Comment by XITRIX** [comment]
Mouse pointer you mean USB mouse or which one? I cannot replicate your issue with touchscreen mouse

**Comment by ShinRaikdou** [comment]
> Mouse pointer you mean USB mouse or which one? I cannot replicate your issue with touchscreen mouse

Yes, USB mouse on PC. When you enable touchcreen mode on the Switch, mouse pointer getting stuck on the upper left of the screen. If you touch anywhere on the screen that pointer appears on the place you touched but returns to the upper left of the screen shorly after.

**Comment by XITRIX** [comment]
Test [this one](https://github.com/XITRIX/Moonlight-Switch/actions/runs/7995709226), please

**Comment by ShinRaikdou** [comment]
> Test [this one](https://github.com/XITRIX/Moonlight-Switch/actions/runs/7995709226), please

No changes.

https://github.com/XITRIX/Moonlight-Switch/assets/33326782/248c09c5-5f89-4742-a872-24ec96d5e781

**Comment by XITRIX** [comment]
I cannot understand what you are doing to reproduce it. Could you please make a video or describe in details what exactly I should do to reproduce it?


https://github.com/XITRIX/Moonlight-Switch/assets/9553519/bbb3c7d8-f1ce-4df9-9ea8-6bb3c605c99c

**Comment by ShinRaikdou** [comment]
I don't understand either. It works on previous version, but to be fair touch registration wasn't perfect and I had to click multiple times.

https://github.com/XITRIX/Moonlight-Switch/assets/33326782/2b28a96e-7ca3-42ea-ab9d-c1262b6edfec

**Comment by ShinRaikdou** [comment]
I wasn't even aware you can use something other than GeForce Exp on Windows :D
I'll try Sunshine later.

As for that new build, now touch control works perfectly, even better than before 1.0 update. Thank you.

**Comment by XITRIX** [comment]
Released in v1.1.0
