### ISSUE TITLE
[Feature Request] Change the rumbling force

### ISSUE THREAD

**Issue by ShinRaikdou** [XITRIX/Moonlight-Switch#137]
After using v1.0.0 for a while, I noticed vibration become way too strong in some games.
Would it be possible to add an option for vibration intensity control?

**Comment by XITRIX** [comment]
Maybe it's a good idea

**Comment by XITRIX** [comment]
Implemented in [latest builds](https://github.com/XITRIX/Moonlight-Switch/actions/runs/7952522053). Try to check it, please

**Comment by ShinRaikdou** [comment]
> Implemented in [latest builds](https://github.com/XITRIX/Moonlight-Switch/actions/runs/7952522053). Try to check it, please

It works! Thank you.

**Comment by XITRIX** [comment]
Released in v1.1.0
