### ISSUE TITLE
[Bug]A touch bug in TouchScreen Mode

### ISSUE THREAD

**Issue by TangXiaoLin-CN** [XITRIX/Moonlight-Switch#140]
You can try using Windows's built-in touch keyboard to reproduce this vulnerability.

The specific manifestation is that after clicking once, the screen keyboard will disappear, and when typing with the built-in touch keyboard in Windows, it will suddenly disappear. Therefore, I guess it is actually a problem with touch events.

**Comment by renA21** [comment]
I think the issue is that the touchscreen mode is still doing mouse clicks like in older builds and touchscreen presses at the same time. There were times where I try to open up the start menu it would randomly click on somewhere else.

**Comment by XITRIX** [comment]
Try to check in [this build](https://github.com/XITRIX/Moonlight-Switch/actions/runs/7952522053), please. I've improved the touch behaviour, now it should support multitouch and should not trigger while onscreen keyboard presented

**Comment by TangXiaoLin-CN** [comment]
> Try to check in [this build](https://github.com/XITRIX/Moonlight-Switch/actions/runs/7952522053), please. I've improved the touch behaviour, now it should support multitouch and should not trigger while onscreen keyboard presented

The vulnerability seems to still exist, consistent with what netizen RenA21 said. When making a touch click, the position of the mouse will also be clicked, resulting in the disappearance of the touch keyboard.

**Comment by TangXiaoLin-CN** [comment]
> I think the issue is that the touchscreen mode is still doing mouse clicks like in older builds and touchscreen presses at the same time. There were times where I try to open up the start menu it would randomly click on somewhere else.

I think you are correct. After testing, the position of the mouse will indeed be pressed

**Comment by XITRIX** [comment]
[More improvements](https://github.com/XITRIX/Moonlight-Switch/actions/runs/7995414688), check it, please

**Comment by TangXiaoLin-CN** [comment]
> [More improvements](https://github.com/XITRIX/Moonlight-Switch/actions/runs/7995414688) to the goddess of improvements, check it, please

At present, it seems to be working very well. Thank you for your hard work

**Comment by XITRIX** [comment]
I'll mark it as "Ready for release", if still need some changes, please, report about it

**Comment by XITRIX** [comment]
Released in v1.1.0
