### ISSUE TITLE
Joycon not working

### ISSUE THREAD

**Issue by lsilvatti** [XITRIX/Moonlight-Switch#141]
Hello everyone, i'm using Moonlight Switch on last ATM and my joycon are not recognized when i enter on steam big picture via moonlight. I'm using Sunshine as streaming client.

**Comment by TangXiaoLin-CN** [comment]
I seemed to have encountered this issue yesterday as well, and it only recovered after restarting

**Comment by XITRIX** [comment]
Not client related issue, try to check if you have [ViGEM driver](https://github.com/nefarius/ViGEmBus/releases/download/v1.22.0/ViGEmBus_1.22.0_x64_x86_arm64.exe) installed

If still need help, feel free to ask
