### ISSUE TITLE
Unable to create forwarders

### ISSUE THREAD

**Issue by Paffo** [XITRIX/Moonlight-Switch#143]
Hi,
I tried to make forwarders both with SAK and with TooTallNate's online tool.
The "just moonlight" forwarder works, but whenever i try to add the arguments to start a game directly, it always fails to launch.
The "NRO Path" set as such: "/switch/Moonlight-Switch/Moonlight-Switch.nro --host=censored --appid=27480384 --appname=Prey" for instance, is it correct or am i missing anything?
And what if the game has a space in the name, like "half life" for instance?

![image](https://github.com/XITRIX/Moonlight-Switch/assets/15388318/96468a09-ee78-4fe5-b25a-db5f6ded067d)

Thank you for porting this great tool and thanks for your patience 👍

**Comment by XITRIX** [comment]
Hi, forwarders not working if you'll use arguments as a part of your path, the only way I was able to create a forwarder was NTON tool with GUI ONLY! There is a field "Arguments", try to create forwarder using it.

It's a shame that there is not so much tools that could create forwarders in proper way, I even thinking of creating my own one

**Comment by Paffo** [comment]
Yeah, NTON works fine, thank you very much!
