### ISSUE TITLE
Connection failed with error “Mode 1280x720x60 not supported” 

### ISSUE THREAD

**Issue by CBCBA** [XITRIX/Moonlight-Switch#146]
Even I set  every different resolution and refreshing rate，it  shows the same error: “Mode xxxx not supported”.How can it make work?
Moonlight-Switch version: 1.0.0
Sunshine version: 0.22.0
![image](https://github.com/XITRIX/Moonlight-Switch/assets/21093644/be4ce9a7-598d-4541-a40b-faf5dd2811a0)

**Comment by XITRIX** [comment]
Duplication #145
