### ISSUE TITLE
[enhancement] keyboard combo hotkeys/buttons

### ISSUE THREAD

**Issue by mcross829** [XITRIX/Moonlight-Switch#15]
I think a cool feature would be some buttons above the on-screen keyboard for common keyboard combos (alt + enter, shift + tab, etc.). 

Hotkeys for keyboard combos would also be cool, like moonlight-nx, but I would really love on-screen buttons for them.

**Comment by XITRIX** [comment]
I’d like to create customizable keyboards, so anyone could create a layout for himself, on any language or with different amount of buttons, adding combo keys type is a good idea for it
