### ISSUE TITLE
cannot connect over internet using moonlight switch

### ISSUE THREAD

**Issue by Azimura82** [XITRIX/Moonlight-Switch#150]
So when I go to connect while using a different wifi from the host's one, it says unreachable
this happens only when connected from a different network (like LTE or a friend's wifi router) 
I must specify that the problem is not my PC or my setup because when I switch to switchroot android and launch the android version of moonlight I can connect without any issues

(also wake on lan just does not work even on the same network, but again it works on switchroot android) 

sorry to bother

**Comment by XITRIX** [comment]
duplicate #161
