### ISSUE TITLE
I hope to be able to add an IPV6 method to connect to Windows

### ISSUE THREAD

**Issue by iwodnfo** [XITRIX/Moonlight-Switch#151]
I hope to be able to add an IPV6 method to connect to Windows
Currently, if you enter the domain name or IP address of IPV6, it will show that it cannot be recognized.

**Comment by XITRIX** [comment]
Switch's HOS does not support IPv6 so it is impossible to implement (At least for Switch platform)

**Comment by iwodnfo** [comment]
> Switch 的 HOS 不支持 IPv6，因此无法实现（至少对于 Switch 平台而言）
Thank you very much for your answers, including your unpaid contributions
