### ISSUE TITLE
[Feature Request] Request for multi-monitor switching functionality

### ISSUE THREAD

**Issue by TickToTock** [XITRIX/Moonlight-Switch#152]
My desktop has 3 monitors, but when I stream my Switch using Moonlight, it only displays on the primary monitor by default. 
Could you please add a hotkey or button to allow switching the stream display between the different monitors?

Thank you.

**Comment by XITRIX** [comment]
Server software (GExperience and Sunshine) does not support such functionality, it is impossible to implement on client side for now

**Comment by TickToTock** [comment]
> Server software (GExperience and Sunshine) does not support such functionality, it is impossible to implement on client side for now. You should manually change settings on server and restart your stream

Thanks for your kind reply.
I was having another issue when streaming from my desktop to switch using Moonlight. It kept displaying the error 'Mode 1280x720/1920x1080 60 not supported' while it worked normally on other devices (Android phones, MacBook, etc.). However, this problem was resolved after I upgraded to the latest 0.22.2 version of Sunshine. Do you know why this issue occurred? I have
noticed a few other issue requests on GitHub where you mentioned it was not related to the Moonlight Switch client itself.

![02](https://github.com/XITRIX/Moonlight-Switch/assets/77729821/c945e2d0-9864-4c27-8ad6-34d1ee382434)
![03](https://github.com/XITRIX/Moonlight-Switch/assets/77729821/313f3387-5359-4374-9d8d-642a925c976a)

**Comment by XITRIX** [comment]
In sunshine was a bug which made server to report the wrong list of supported resolutions. There was no issues on other clients, because they ignore the fact of incompatible resolution and tried to "negotiate" it later during connection, while Moonlight-Switch requires resolution to match exactly as it want.
