### ISSUE TITLE
Switch Moonlight Bad Connection

### ISSUE THREAD

**Issue by flowey41** [XITRIX/Moonlight-Switch#153]
When I try to connect my Switch to a game on GeForceExperience, it says bad connection. I have 5GHz Wifi and have updated everything switch related, please help if you can

PS: If it helps, my best download speed until now was around 5mb/s when connected trough wifi, which is the case for my switch. My PC is connected to my router trough ethernet and has the download speed of 48.80mbps (? or upload speed: 9.95mbps)

**Comment by XITRIX** [comment]
From Discord channel I can see that you are using not Moonlight-Switch, but Moonlight-NX. I recommend you to install latest version of the app from this repo first
