### ISSUE TITLE
V1.0.0 Rumble Vibration so much loud with buzzing (NS OLED) 

### ISSUE THREAD

**Issue by alquadaur** [XITRIX/Moonlight-Switch#154]
Hi, I have two Switches Rev1 and OLED
On rev 1 good vibro all is ok, but at oled I Have so much loud vibro with buzzing.
I tryed to download Moonlight 0.13.4 and I got good vibration. 
I think you just need to add option for change max vibration level for fix it. (Low (just like in v0.13.4) or Default (just like in v1.0.0) 

Maybe it's my joy-cons issues, but i think this option is good idea for users, who wants make vibro weaker or stronger.

And Thanks for this app for Switch. It's add new functions for my favourite portable console :)

**Comment by XITRIX** [comment]
Download [latest development build](https://github.com/XITRIX/Moonlight-Switch/actions/runs/8421365548), it contains rumbling force setting so you can reduce it if you want
