### ISSUE TITLE
doesn't show the games

### ISSUE THREAD

**Issue by Elitepanther1** [XITRIX/Moonlight-Switch#156]
So, I setup the connection with my switch over LAN, when I go to launch a game, it launches it without issue, but it never shows in the switch, I click on the game that I want to play in the switch or even steam, it launches on the pc, but on the switch it gives the loading animation and after a few seconds it goes away and nothing happens, it shows that the application is running but it just doesn't open it on the switch.

**Comment by XITRIX** [comment]
Not enough info, attach screenshots pls.

Are you using Nvidia Experience or Sunshine?

**Comment by Elitepanther1** [comment]
It got fixed by itself, I think my PC needed a restart.
