### ISSUE TITLE
[enhancement] Improved mouse input mode + gyro mouse

### ISSUE THREAD

**Issue by billyea** [XITRIX/Moonlight-Switch#16]
For people who use Moonlight for their desktop, the experience is less than ideal.

The mouse input mode is the only one where the mouse cursor moves slowly enough to hit targets. The mouse input mode needs to be enabled from the side menu on session start, and puts a big button guide on top of the stream while you're using it. The mode can also be enhanced with more precise pointer/gyro controls.

Suggestions:
- make the button guide appear in the side menu or separate options page, instead of overlaid on the stream
- allow mouse input mode to be set as the default mode for the entire application or for specific apps
- add option to enable gyro mouse controls (as the default mode for the entire application or for specific apps)

**Comment by XITRIX** [comment]
For precise input, you can press  LB or RB to slow down or raise the speed of cursor.

In next updates I'll try to implement favorite apps with individual settings, it's a nice idea to add there an option to launch it in mouse input mode.

Also I could add a setting to hide guide panel in mouse input mode.

**Comment by billyea** [comment]
When I was trying it out, LB/RB only worked to change cursor speed when mouse input mode was enabled. They did not change cursor speed without it enabled. Is this intended behaviour?

**Comment by XITRIX** [comment]
Yes, I never experienced any difficulties with touchscreen mouse input, so I have not thought about changing speed for touchscreen cursor. If it could cause any problems, I could add a slider for mouse speed inside overlay menu, like audio slider, which already there.

**Comment by billyea** [comment]
Could be helpful to add it in general settings as well. Settings in the overlay menu are a few extra steps compared to starting the stream just the way you want it. I do appreciate your consideration though.

**Comment by XITRIX** [comment]
I thought again about your suggestions and made a decisions:
- I have added mouse acceleration setting, it's available in [v0.9](https://github.com/XITRIX/Moonlight-Switch/releases/tag/v0.9) 
- I'll add an ability to set different settings to apps in Favorite list later
- I don't think I'll change a behavior of mouse input mode any time soon, it's just an accessibility feature, and not been made as a primary input mode, so you need to know that it's active. May be I'll change it later.
- Gyro mouse is also a very hard to implement, I'll think about it, but cannot promise anything

**Comment by XITRIX** [comment]
Native gyro input implemented in v1.0, gyro for mouse input is not planned
