### ISSUE TITLE
默认映射为Ps4手柄，我希望提供映射为Xbox手柄的选项

### ISSUE THREAD

**Issue by Shaw9** [XITRIX/Moonlight-Switch#162]
如标题所说
默认映射为Ps4手柄，我希望提供映射为Xbox手柄的选项，谢谢

**Comment by XITRIX** [comment]
Gyro is supported only with PS4 controller layout, if you do not case about it, you can configure your Sunshine to force using Xbox layout (Change preferred controller layout from Automatic to Xbox)
