### ISSUE TITLE
[BUG] Performance-Related Stuttering (like using high bitrate but not overclocked), But Incorrectly Tipped as "Bad Connection"

### ISSUE THREAD

**Issue by Kane-Kuroneko** [XITRIX/Moonlight-Switch#168]

**Comment by XITRIX** [comment]
"Bad Connection" message appears if there are delays between frames and it does not matter how this delay appeared (by networking issues, or performance). It is barely possible to distinguish them so it is expected behaviour and not something that I am going to fix

**Comment by Kane-Kuroneko** [comment]
It is certainly important, as we need this message to distinguish what caused the stuttering or latency.

**Comment by XITRIX** [comment]
As I said, there is no way to understand the source of the stutter from application side, all I can do is just change the message to something like "Bad Connection or OC required"
