### ISSUE TITLE
[Bug] Overlay combo can only be set in portable mode

### ISSUE THREAD

**Issue by billyea** [XITRIX/Moonlight-Switch#17]
When trying to configure the in-game overlay button combo with the Switch docked to the TV, there is no way to exit the dialog box or confirm the combination. Pressing a button just adds it to the combination. The only way to exit is to pick up the Switch and use the touch screen to close it.

Suggestions:
- add an exclusive shortcut to close this box
- warn the user that opening the dialog box should only be done in portable mode

**Comment by XITRIX** [comment]
I know about that problem, but I'm still not sure what is the right way to deal with it...

May be I'll unfreeze "L" stick and "A" button to make it possible to select on option on dialog view.

**Comment by billyea** [comment]
Another option is to have dialog auto-accept after a certain countdown. Paired with a reset to default button in the main menu for accidental mistypes.

**Comment by XITRIX** [comment]
Fixed in [v0.9](https://github.com/XITRIX/Moonlight-Switch/releases/tag/v0.9)
