### ISSUE TITLE
[Feature Request] 480p / custom resolution setting

### ISSUE THREAD

**Issue by josephsmith0705** [XITRIX/Moonlight-Switch#174]
The 3DS moonlight port has really low latency - I think this is because it’s set up to 480p so can use a low bitrate, and isn’t hard to decode / render. It’d be ace if we had a 480p option in this app, to reduce the visual quality in exchange for better latency.
I intended to do this myself as it seemed relatively simple but had issues building the nro (cmake couldn’t find any of my package libraries, like curl library) so raising this here instead

**Comment by XITRIX** [comment]
Implemented in v1.2.0
Added 360p and 480p resolution options, as well as 45 FPS option.
If custom resolution setting is still required, feel free to reopen this issue
