### ISSUE TITLE
Touchscreen not working properly with some software

### ISSUE THREAD

**Issue by imkrut** [XITRIX/Moonlight-Switch#175]
Some software ignores touch input.

For example, I have a dual screen setup when running 3DS games on my pc, and I stream the secondary screen to the switch to use as a touchscreen, however the touch input is completely ignored on Citra (if I use the mouse or the analog to manually move the cursor it works fine tho).

**Comment by SwimmingTiger** [comment]
If you use Sunshine streaming server, you can configure it to solve the problem:

Configuration > Input > Native Pen/Touch Support > Disabled.

![image](https://github.com/user-attachments/assets/08abc82b-50fa-4f95-b2ba-11944c895039)

**Comment by imkrut** [comment]
> ![image](https://private-user-images.githubusercontent.com/4986069/354305913-08abc82b-50fa-4f95-b2ba-11944c895039.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNDEyOTgsIm5iZiI6MTcyNjI0MDk5OCwicGF0aCI6Ii80OTg2MDY5LzM1NDMwNTkxMy0wOGFiYzgyYi01MGZhLTRmOTUtYjJiYS0xMTk0NGM4OTUwMzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMTUyMzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWZlOGYyMjcwNTg2Y2QwZWQ3ZTQ5ZmYyZjA2NTQyYTRhNGU2Mzk5YWJkZWEwYzc3NWU0YzViZGExZTc2MTU3YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zhZ-l3TZYVZWrJ9ytKDrEGZPV7HQSBjLTD7mo6ywt6k)

That does work perfectly, but sunshine has it's own problems (related to screen rotation). Is there any way this can be applied without using Sunshine?=
