### ISSUE TITLE
Swiping on the left side of the screen sometimes opens the in-game overlay

### ISSUE THREAD

**Issue by RadarNyan** [XITRIX/Moonlight-Switch#177]
Is this by-design? If so, I'd like to have an option to disable it since it interferes with touchscreen input.

The most reliable way I've found to reproduce this is to put the finger on the top left part of the screen, hold for about 5 seconds, then swipe diagonally down to the lower right. If done correctly, this would trigger the overlay screen (which you get when pressing the - & + buttons simultaneously by default)

**Comment by XITRIX** [comment]
Yes, it's on purpose, in case you use the switch as tablet, you will be able to open overlay without controllers, but you are right, I need to add setting to disable it (or enable it only if there is no controllers attached)

**Comment by XITRIX** [comment]
Implemented in v1.2.0
Now this gesture will only work if there is no connected controllers
