### ISSUE TITLE
v1.2.0 causes distorted audio at any bitrate

### ISSUE THREAD

**Issue by Lewewe** [XITRIX/Moonlight-Switch#181]
After upgrading to v1.2.0, suddenly the sound is very disturbing and the rumble doesn't stop even after terminating any app, only when closing the app does the problem get fixed
Hope you can find a way to fix it

**Comment by XITRIX** [comment]
Looks like some of DevKitPro packages was broken with update (probably SDL2), I reverted all of them back to state of v1.1.0, so now it should work.
Check the release v.1.2.1 please
