### ISSUE TITLE
Moonlight starts detecting Joycons as Playstation controller to start, then after restart is detected as XBox controller

### ISSUE THREAD

**Issue by StarBoundBard** [XITRIX/Moonlight-Switch#193]
I have an Atmosphere OS installed Switch that I installed Moonlight on a few weeks ago, works fantastic other than this one quirk. 

When I first start Moonlight, my joycons are detected as Playstation controls. This also seems to screw up some of the bindings.

When I simply close / reopen, or fully restart Moonlight, the controls are correct, both in detection and my bindings.

**Comment by XITRIX** [comment]
It should be recognized as PS4 controller to allow GYRO to work (Xbox controller has no GYRO support), so I would say that it started to recognize as Xbox is a bug, not the opposite.
But if you want Moonlight to be recognized as Xbox controller, you can change that setting in Sunshine itself.

**Comment by StarBoundBard** [comment]
Thank you for a lightening fast response and explanation, I was sure I was missing something :) 
I will take a look when I get back home & trial configuring it as a Playstation controller instead of Xbox!
