### ISSUE TITLE
[enhancement] Steam Overlay

### ISSUE THREAD

**Issue by vos6434** [XITRIX/Moonlight-Switch#2]
Holding down the Minus button for 3 seconds opens up steam overlay.

**Comment by XITRIX** [comment]
I am thinking about pressing "-" and "+" buttons simultaneously, but I think I'll make an option to select the preferred way to open it.

**Comment by vos6434** [comment]
hm so instead of a dedicated button for steam overlay, you could add a steam overlay button in the moonlight overlay?

**Comment by XITRIX** [comment]
Done, released in v0.5.
You could select your own button combination and time you'd like to hold them to open overlay in Settings tab.

**Comment by vos6434** [comment]
oh no I didn't mean change the moonlight overlay, I was asking for **steam** overlay support.

**Comment by XITRIX** [comment]
If you mean "Guide" button, I also added it

**Comment by vos6434** [comment]
I guess i do mean it but it opens windows game bar, not the steam overlay. Can you add an option that opens the steam overlay instead.
