### ISSUE TITLE
 19.0.1 Error reporting

### ISSUE THREAD

**Issue by Avaxiaoxu** [XITRIX/Moonlight-Switch#201]
excuse me，version 19.0.1 cannot be used?

**Comment by XITRIX** [comment]
I have no idea, I'm still using 18.x
Better ask it on Discord channel, probably someone already tried to run it on 19.0.1

**Comment by XITRIX** [comment]
I was told that app works fine on 19.0.1

**Comment by Avaxiaoxu** [comment]
I recreated it and it worked fine when opened HBMenu. It’s perfectly solved. Thank you for your help : )
