### ISSUE TITLE
Need ipv6 support

### ISSUE THREAD

**Issue by bowen26222** [XITRIX/Moonlight-Switch#206]
hi! I have ipv6 address and I can connect sunshine by my phone but I cant input my ipv6 address in ns version.
Can you add ipv6 support to your version, or it is easy to modify code to make it? I haven't read the source code.

**Comment by XITRIX** [comment]
You are saying about app version for Nintendo Switch?

**Comment by bowen26222** [comment]
Yes, I said about app version for ns. And I think maybe it doesn’t have ipv6 support because ns system doesn’t support ipv6. I just hear other one said ns just can access to ipv6 by use android version moonlight on android.

**Comment by XITRIX** [comment]
Yes, HOS does not support IPV6, you can use it only with Android, but Moonlight-Switch has no Android version.

P.S. Moonlight-Switch does support IPV6, but only in iOS version of app
