### ISSUE TITLE
[Bug] Error texts contains unknown symbols

### ISSUE THREAD

**Issue by lightsabata** [XITRIX/Moonlight-Switch#22]
Characters error on timeout message. 
Using homebrew on switch lite CFW 13.0.0 atmosphere 1.1.1 (French language system menu, don't know if it's related)

![2021100105450500-11B102D2D9F8C26297FA788A42CC9784](https://user-images.githubusercontent.com/43295382/135562240-206c3fa4-254c-47f7-baeb-12d0055dc979.jpg)

**Comment by XITRIX** [comment]
This symbol is just \n and I cannot understand why it looks like this...
I think it's because all errors are lot localized, I'll try to translate them later, hope it will fix that

**Comment by XITRIX** [comment]
Fixed in [v0.9](https://github.com/XITRIX/Moonlight-Switch/releases/tag/v0.9)
