### ISSUE TITLE
[Enhancement] keyboard arrow keys

### ISSUE THREAD

**Issue by windraver** [XITRIX/Moonlight-Switch#23]
It would be nice to be able to input the keyboard arrow keys.

Scenario:
When loading some games (example genshin impact), they popup the "Do you want to allow this app to make changes to your device?". The mouse cursor disappears (this happens for all moonlight ports) and so a keyboard arrow keys input allows the user to easily select "Yes"

**Comment by XITRIX** [comment]
I thought about making an ability to create a user provided keyboard layouts (for different languages i.e.), and as example I thought to create a full sized desktop keyboard with arrows and all other stuff

**Comment by XITRIX** [comment]
And as Genshin player, I recommend you check [this](https://www.tenforums.com/tutorials/57690-create-elevated-shortcut-without-uac-prompt-windows-10-a.html?__cf_chl_jschl_tk__=pmd_VWCF6zCfJnhx.DZXPp65jPA86poBo..P82umcvtoP6E-1633253042-0-gqNtZGzNAjujcnBszQb9) out ;)

**Comment by haruupi** [comment]
It’s possible to add a second page of symbols? There’s no hyphen or underscore available on the keyboard, other option would be to be able to launch the switch keyboard itself, if it’s possible. (I’m trying to login in Genshin Impact)

**Comment by Kennnwxyz** [comment]
Do this and you can still see your cursor

![image](https://user-images.githubusercontent.com/104927126/166791774-5f76e33d-8b07-4599-a7af-25ab1e3c9a51.png)

**Comment by XITRIX** [comment]
It will lower your PC protection, I'm highly recommend not to do this. I've already implement full desktop keyboard layout, you could try it here
