### ISSUE TITLE
low volume scale

### ISSUE THREAD

**Issue by eyunha** [XITRIX/Moonlight-Switch#3]
I really appreciate to you about making this as a good UI,
but sound volume scale is too low although I turned volume up on my switch.
I wish rock88 would correct this problem, but no updated. 
Please solve this problem. I think it might be problem about audio render.

**Comment by XITRIX** [comment]
Ok, I'll take a look on it.

**Comment by eyunha** [comment]
Really? I definitely turned up through my PC setting such as volume of all devices including Nvidia output.
so if you are right, I assume it depends on installation status of Nvidia driver. I’ll also check driver or status for Nvidia device.
Thank you so much.

**Comment by yaseen420** [comment]
I second this. Both rock88, and this one have low audio scale. 

This one more odd thing I noticed. rock88's version has an issue where audio desyncs if the stream stutters. More stutters = greater delay. This version doesn't have any issues like that, I'm happy to say. 

However, there seems to be a greater audio delay than rock88's version. Like if audio was 15ms for rock88's, this one is around 50ms (not accurate numbers, just guesses). I did a little comparison between the two, and this definitely stands. It's no big deal for me personally, but just thought I'd put it out there. 

Overall, prefer this version over rock88's in so many ways. Great work!

**Comment by XITRIX** [comment]
Thanks for your nice words!

I know about problem with audio desync in rock88's version, so I'm using different audio decoder with fixed issue, may be it's a bit slower in processing, so greater delay appears, but problems with sound scale is really strange, my switch is really loud on high volume. 

Have you tried to run moonlight on another devices (i.e. laptop), does sound works well there?

**Comment by yaseen420** [comment]
Really appreciate that you changed audio decorder to prevent the audio desync. It was driving me crazy on rock88's version. 

Also now that you mentioned it, I did try it on my PC (my PC to someone else's), and the audio was quiet, when compared to discord screenshare for example. So it could just be a moonlight thing, but as you mentioned, a 200% slider would be great (if possible)!

**Comment by XITRIX** [comment]
Yes, I think it's possible, but I'm not sure about good sound quality with it. Try to play with audio settings on your host machine, there should be a virtual sound device, may be its volume is low. 

Right now I'm a bit busy to work develop app, so I'm not sure how long implementation of that slider will take, better to fix it on your host machine.

Oh, you can also try to enable "Play audio on PC" setting, it should start to use your primary audio device as output, you could plugin your headphones to silent your PC, may be it could help to solve your problem with volume.

**Comment by yaseen420** [comment]
No worries, I appreciate the reply. I was using my earphones, and the audio through them seemed fine (had to turn it to the max though). I already have "Play audio on PC" checked. 

Just looking forward to the updates in the future, keep developing!

**Comment by XITRIX** [comment]
I've found some time to implement that feature, it is now released in v0.6.

By default only 100% volume scale is allowed, to unlock amplification, open settings and enable "Allow volume amplification" option. Then the maximum value of volume slider will have 500% value.

Hope it will help you!
