### ISSUE TITLE
Box arts not loaded

### ISSUE THREAD

**Issue by Vaddum** [XITRIX/Moonlight-Switch#30]
Hi! Since release v0.10 personalized box arts (downloaded on steamgriddb.com) do not show properly. I do not know why but it may be due to the size of the image files. Cheers!

**Comment by XITRIX** [comment]
Hi, could you attach an example of broken art, so I could test it by my self?

**Comment by Vaddum** [comment]
For instance, here is the box art I downloaded for Deadlight which does not show in Moonlight-Switch.
![Deadlight](https://user-images.githubusercontent.com/67381438/138043639-ab9ea63f-2a40-414a-870c-df5546b82af6.jpg)
