### ISSUE TITLE
Add it to the homebrew appstore

### ISSUE THREAD

**Issue by badbcentral** [XITRIX/Moonlight-Switch#32]
Hey! Love your app!
Please add it to the app store, so it's easier to update it.
Also, I have an idea, idk where to submit it.
Would it be possible to implement touchscreen? Is it possible to create an additional server application that'll be running on a PC and that will be communicating with a running alongside functionality in the app, and this way it'll be possible to process the touch?
And also motion control support.
This way, it'll be possible to throw cemu's Wii u gamepad image on switch by moonlighting a virtual/additional monitor  to switch and kinda making a Wii u setup like that.

**Comment by XITRIX** [comment]
Hi, I'd be happy to add it to homebrew appstore, but I don't know how :/

Also it's a good idea about touchscreen, I've also thought about possibility of doing that, I'll try to investigate something to make it possible

**Comment by badbcentral** [comment]
@XITRIX https://submit.fortheusers.org/ держи

**Comment by XITRIX** [comment]
@badbcentral, отлично, спасиб!

**Comment by badbcentral** [comment]
@XITRIX можешь дать свою телегу / Дискорд?

**Comment by XITRIX** [comment]
@badbcentral XITRIX#0153

**Comment by badbcentral** [comment]
@XITRIX не очень хорошо что создаётся папка moonlight в папке switch, и она видна в hbl

**Comment by badbcentral** [comment]
@XITRIX ну надо сделать что-то с релизом из стора, чтобы он скачивался в правильную папку

**Comment by badbcentral** [comment]
@XITRIX со стора он скачивается в папку Moonlight-switch, при этом данные проги хранятся в moonlight

**Comment by XITRIX** [comment]
поменял папку для хранимых файлов, теперь всё должно быть ок
