### ISSUE TITLE
[Localization] - {Chinese simplified}

### ISSUE THREAD

**Issue by PenguinQuin** [XITRIX/Moonlight-Switch#34]
I want to translate Chinese (simplified). My poeditor name is Quinn.

**Comment by XITRIX** [comment]
You are welcome!

**Comment by spacemeowx2** [comment]
Seeing that the progress of Chinese on POEditor is 100%, I am looking forward to see the release of Chinese support. Thank you both for your excellent work!

**Comment by XITRIX** [comment]
I'll add it in next release

**Comment by XITRIX** [comment]
v0.11 released
