### ISSUE TITLE
[Feature Request] Hide Games on Moonlight

### ISSUE THREAD

**Issue by greensad** [XITRIX/Moonlight-Switch#35]
Would be great to have the ability to hide games as I have several duplicates

**Comment by XITRIX** [comment]
I think it's not a good idea, cause I'll need to add the way to show hidden titles in case of removing them from hidden list. Better add titles you are using more often than others in favorite list

**Comment by greensad** [comment]
It would be nice to have since using favorites can't hide dupes if I only have a few games added but if it's out of scope feel free to close the issue, particularly since I don't really use moonlight anymore :)
