### ISSUE TITLE
Is it possible to pair 2 different controllers?

### ISSUE THREAD

**Issue by ncesar** [XITRIX/Moonlight-Switch#37]
I plan i playing It Takes Two and I would like to know if I can pair my joycons and my ps4 controller as well.

**Comment by XITRIX** [comment]
It's now in development, next version will support it as well as joycons connected as half.
It already in master brunch, so if you could compile app by your self, you already could try it (or if you'd like, I can compile it for you)

**Comment by ncesar** [comment]
Awesome, thanks for your great job here Xitrix. I will wait for the release since I'm not playing much atm
cheers!
