### ISSUE TITLE
Cemu through moonlight 

### ISSUE THREAD

**Issue by marulovinia** [XITRIX/Moonlight-Switch#39]
Hey there,

I was wondering if it was possible to control cemu at all through Moonlight.

I've naturally tried it but it doesn't seem like any of the inputs register in cemu from the switch, any idea how to fix this or if I did anything wrong?

**Comment by XITRIX** [comment]
I never used cemu, but if it could handle controllers, it should work

**Comment by marulovinia** [comment]
Ahh it works now, for some reason despite previously working I had to reboot my pc a couple times to get the switch to work with ANY game, not just cemu. So just user error!
