### ISSUE TITLE
Crashes when populating game list 

### ISSUE THREAD

**Issue by adam-fox** [XITRIX/Moonlight-Switch#40]
After the first connection to my PC Moonlight crashes when populating my list of games. This usually happens as soon it gets to the third row of games. On the latest Atmosphere and FW.

**Comment by deeptuuk** [comment]
me too

**Comment by XITRIX** [comment]
Are you running Moonlight with full ram access?

**Comment by adam-fox** [comment]
Is that just done by holding R while launching the app? If so, yes i’ve tried with no luck.
