### ISSUE TITLE
Launch hbmenu over Title Redirection (for FULL RAM access);

### ISSUE THREAD

**Issue by deeptuuk** [XITRIX/Moonlight-Switch#41]
I am new about switch，could you tell me how to run moonlight in  FULL RAM?

**Comment by deeptuuk** [comment]
I don't know how to Title Redirection

**Comment by XITRIX** [comment]
You could install [Hekate Toolbox](https://github.com/WerWolv/Hekate-Toolbox/releases/tag/v4.0.1) and select the way to start hbmenu with full ram access.

**Comment by kokototo13** [comment]
Thank you! it worked even in January of 2025
