### ISSUE TITLE
2 controllers issue

### ISSUE THREAD

**Issue by MAN-biker** [XITRIX/Moonlight-Switch#42]
I can't use TWO controllers (a pair of loycons + Pro compatible controller.
In the PC devices panel i see onle ONE "Virtual USB Device".
BOTH controlles works fine with Moonlight as SINGLE (or 1st controller in system).
Both controllers works file at the SAME time in **SkyNX**, but not with Moonlight.

**Comment by XITRIX** [comment]
This functionality was not released yet, so if you are using latest release version, it will not work. You could try to compile app from source code, or you can download beta binaries from our discord server. Then several controllers should work

**Comment by MAN-biker** [comment]
Thanks for answer, but I have no idea how to compile app from source code by mysels and cant find any builds for SWITCH at Discord (there are many one for Android, Linux etc., but NOT switch. Help me, plz. Thanks.

**Comment by XITRIX** [comment]
https://drive.google.com/file/d/1yGlsEgvhyW6QTQxIkmVugz8sAXi6rapJ/view?usp=sharing

**Comment by XITRIX** [comment]
I've released v0.11 with multiply gamepad support, so now you could use it!
