### ISSUE TITLE
Crashing (Atmosphere Error) when launching from Title Screen

### ISSUE THREAD

**Issue by en0l1c** [XITRIX/Moonlight-Switch#44]
As I say in the title. The App crashing when Im clicking to open it from hbmenu (from Titles Menu), but if I open it from Album app it is working perfectly. May I have problem with RAM if I using it from Album app and not from hbmenu ?
![IMG_2021-12-25-06-43-35-770](https://user-images.githubusercontent.com/34587857/147377583-7025a6b5-3c21-481a-8e67-c304efa5e10c.jpg)

**Comment by en0l1c** [comment]
Basically, I saw right before the error coming to all homebrew apps opened from hbmenu at Titles Menu. 
It is not problem from the moonlight.nro

So, the hbmenu created automatically when I click to open moonlight.nro from SD card. It is related with? 
What can I do to solve the problem?

Thanks in advance!!

(Keep your fantastic work!)

**Comment by XITRIX** [comment]
The only thing I could recommend is to reinstall atmosphere from scratch, update hbmenu nro file and try to use Hekate-Toolbox to properly configure title redirection.

**Comment by en0l1c** [comment]
May I have problem if I am keep playing from Moonlight that exists in Album app?

**Comment by XITRIX** [comment]
Yes, you could, applet mode has limits on RAM usage, so it could crash if app will exceed the limit. Some times I had Atmosphere crashes using moonlight via Album app, but as I can see, it could differ from user to user

**Comment by enriquegm** [comment]
Last hbmenu, last Atmosphere, Launch with full RAM, Last firmware... Same issue... Could it be a problem with the firmware?

![image](https://user-images.githubusercontent.com/8687930/209486119-85ee726f-609f-4297-8157-f3d377bdd552.png)
![image](https://user-images.githubusercontent.com/8687930/209486147-69ad8c98-5740-46c5-97f3-1d6982237dc4.png)

**Comment by enriquegm** [comment]
By the way, great port, thanks for developing it. :)

**Comment by XITRIX** [comment]
@enriquegm, that's strange logo, there should be author: XITRIX, and apps version the same like releases on GitHub (there is no 1.0.0 version yet)

**Comment by XITRIX** [comment]
It should be like this:
![IMG_6181](https://user-images.githubusercontent.com/9553519/209528353-b6ac931a-976f-4466-94da-73ab38103733.png)

**Comment by enriquegm** [comment]
You're right, I was trying the Rock88 version and it must have stuck.  Version 0.12 works for me. But something strange happens to me, because when I launch it from tinfoil it goes without problem, but with the hbmenu it doesn't :?

Thanks for the tip :)

**Comment by XITRIX** [comment]
What do you mean "from tinfoil"? Tinfoil should not be able to run homebrews, you meant that you are holding R while launching tinfoil?
If so that calls "title redirection" and it allows to run homebrew with full RAM access, also if you meant "with the hbmenu" just launching it via photos applet, that calls "applet mode" it has limited RAM access so app will possibly crash in case it will have no enough RAM
