### ISSUE TITLE
info when runing Game:  Mode 1280*720*30 not supported

### ISSUE THREAD

**Issue by Fan26278** [XITRIX/Moonlight-Switch#45]
PC  server is OpenStream 
I enter the IP , I can see the PC, and I choice OpenStream,   normally at all ,choice Game(Desktop) at Open Stream ,then the moonlight client displays me the following message : "Mode 1280*720*30 not supported"
I tryied change resolution at PC or switch , it shows the same meesage:" 1920*1080*60" not supported

Switch info:  13.2.0|AMS 1.2.5
Moonlight info: v0.11

Thank you for Moonlight on switch

**Comment by Fan26278** [comment]
![image](https://user-images.githubusercontent.com/96853621/147719297-9374682f-0a90-4de7-bcc9-e5eb40c096c8.jpg)

**Comment by XITRIX** [comment]
I've not tried to use OpenStream. Could you confirm that it's not your host issue by trying to connect to it with any other moonlight client (for android or ios, depends on what phone you have)?

**Comment by Fan26278** [comment]
Thanks for your reply.
I tried to use by iPhone , it's work  normally.

**Comment by Fan26278** [comment]
![image](https://user-images.githubusercontent.com/96853621/147727559-31d3ebb7-f791-4cd7-8e4f-35954108b27f.png)
This is  OpenStream dialogue

**Comment by XITRIX** [comment]
According to this log, looks like it's openstream issue, it could not bound the port [48010] cause something is already using it. Try to find out what app is using it

**Comment by mtheall** [comment]
I ran into the same problem. Openstream server doesn't report any DisplayMode xml in its curl response. But it worked just fine if I set these to true, thereby skipping the mode compatibility checks:
https://github.com/XITRIX/Moonlight-Switch/blob/2a2ff3e345eeb050a0b264ab184a0317ce9015c6/app/src/libgamestream/client.cpp#L440-L441

**Comment by djpanajm** [comment]
hello, i honestly don´t have a clue on how to edit these archieves, do you have the edited version? i mean just de .nro file with those modifications, thank you

**Comment by safarirat** [comment]
I got same error.
But 3 sunshine instance was open on my PC.

**Comment by Duglim** [comment]
> I got same error. But 3 sunshine instance was open on my PC.

Had the same with Sunshine (Linux) and found that there seems to be a bug in sunshine with the "advertised resolutions" values. The last resolution entry in sunshine web gui will be wrong in the XML sent to moonlight.
Try adding an additional advertised resolution in sunshine, even if it's fake. In result, all other values will be correct in the XML afterwards.

**Comment by XITRIX** [comment]
Closing it is as not client related
