### ISSUE TITLE
Bad network connection

### ISSUE THREAD

**Issue by cristianrz** [XITRIX/Moonlight-Switch#55]
Not sure what I'm doing wrong here, trying to play with:

* a laptop connected with gigabit ethernet to a LAN and
* the switch with 5GHz Wi-Fi about 5m away from the router
 
and it says I've got bad connection and lags too much. Using an Android phone with the moonlight app from Android doesn't complain and there's virtually zero lag.

Any ideas?

**Comment by cristianrz** [comment]
Just played a bit with the settings and on Android I can push it up to 50Mbps and it's still zero lag, whilst on the Switch 10Mbps already struggles.

**Comment by XITRIX** [comment]
What resolution you are using?

**Comment by cristianrz** [comment]
720p

**Comment by XITRIX** [comment]
what codec you using?

**Comment by cristianrz** [comment]
Just did some more tests and the issue magically disappeared (?).

It is still slower than Android (can't tell how much but I'd say not more than 50 ms) but I guess that'd be expected?

**Comment by XITRIX** [comment]
Yes, I think so, Switch homebrews have no access to NVENC (hardware video decoder), so it uses software decoder, while Android (as I know) could use it, so it's a bit faster
