### ISSUE TITLE
[Addition] direct tap to click for mouse

### ISSUE THREAD

**Issue by snowyzia** [XITRIX/Moonlight-Switch#57]
In moonlight-nx there's a feature where if you tap on the screen the mouse goes to exactly where you tapped and clicked, I cant find the settings here so I assume its not in it? If it is in please let me know if it isn't it would be a nice addition.

**Comment by XITRIX** [comment]
This mode was really hard to use for me because UI elements in Windows is really small, so I decided not to implement it. But if someone really needs it, ok, I'll try to add it later.

**Comment by BastienClermont** [comment]
Hi @XITRIX , I am very interested in this feature too, I play point-and-click games that make this feature a must have. If you could please implement it it would be amazing! Thank you for kipping this homebrew alive, you're a star :-)

**Comment by XITRIX** [comment]
Ok-ok, you persuaded me:) I'll implement it later, I'm a bit tired from coding and need some rest

**Comment by KadrHF** [comment]
Like BastienClermont said thanks for keeping this alive

**Comment by gricardo93** [comment]
Yeah, this is a very needed feature. Thank you for the Switch port @XITRIX

**Comment by XITRIX** [comment]
Implemented in v1.0
