### ISSUE TITLE
[Feature Request] Work with host controller

### ISSUE THREAD

**Issue by temporaryna** [XITRIX/Moonlight-Switch#59]
The reason is, I'm using it on the same room, and my host is not so far.
So I could use more comfortable controller for example xbox elite controller.
But on some games it seems to be disabled by default. May be because of moonlight using 1st slot by default and host controller using the 2nd slot? ([ref](https://www.nvidia.com/en-us/geforce/forums/discover/231059/possible-to-use-controller-connected-to-pc-while-using-gamestream-/))

Would be great to have this option to toggle in settings (f.e. Use host controller as main)

does it possible on other moonlight platforms like android, linux (through switch priority)? dunno

**Comment by mmelnic** [comment]
Also I found that on Steam settings, on using Moonlight, it says that 2 controllers connected, and the 1st one is Switch, and the 2nd one is Host controller (tested with Found controller rumble feautre, both seems work fine, but controls the game only the 1st one)

https://prnt.sc/scs1Go1oviZw

**Comment by XITRIX** [comment]
I think you could use Mission Control to connect your xbox elite controller to Switch itself. Your use case is VERY specific, normally, games should contains an option to chose controller you'd like to use with it, also you could try to disable them via steam or windows control panel.
