### ISSUE TITLE
Black bars when streaming from 1920x1080 host

### ISSUE THREAD

**Issue by shadowblade227** [XITRIX/Moonlight-Switch#60]
Hello

I tried streaming a non-fullscreen app from my PC with a 1920x1200 monitor, and everything was stretched horizontally, with the image filling the SWITCH 16:9 screen. Since the app (rpcs3) is still 16:9, I decided to put a 1920x1080 resolution on the host pc, but the Switch only added extra black bars like on a 16:10 monitor, and the horizontal stretching didn't go anywhere. Fullscreen apps are fine, but that thing with ps2 and ps3 emulators or just desktop...

What can I do?

**Comment by XITRIX** [comment]
Have you resolved your problem?

**Comment by shadowblade227** [comment]
> Have you resolved your problem?

Yes, changed resolution and stretching typenin nvidia control panel
