### ISSUE TITLE
[Localization updated] Traditional Chinese strings for 0.11

### ISSUE THREAD

**Issue by qazrfv1234** [XITRIX/Moonlight-Switch#61]
Hello,
the attachment for Moonlight-Switch v0.11  (base on the latest en-us/main.json )

[zh-Hant.zip](https://github.com/XITRIX/Moonlight-Switch/files/8371632/zh-Hant.zip)

Many thanks,
Leo

**Comment by XITRIX** [comment]
Added it, thanks!
