### ISSUE TITLE
Chinese simplified have rong display

### ISSUE THREAD

**Issue by momikiii** [XITRIX/Moonlight-Switch#63]
Hi,XITRIX

I have some problem in your app

Chinese simplified have rong display , and I can't alter language to English, hope you can fix it , and add an options to change language

Thanks a lot！

**Comment by XITRIX** [comment]
What do you mean "wrong display"? I don't know Chinese and this language was added by community, so I cannot confirm is it ok or not. Anyway option to change inapp language is planning.

**Comment by Starry-2000** [comment]
Some Chinese character are not displayed correctly, they are vacant. In my experience this is not a translation problem, this should be a lack of corresponding fonts
![image](https://user-images.githubusercontent.com/49426644/163705446-6f47a80d-0daa-41d4-be53-f4b2eaf44907.png)

**Comment by momikiii** [comment]
> Some Chinese character are not displayed correctly, they are vacant. In my experience this is not a translation problem, this should be a lack of corresponding fonts ![image](https://user-images.githubusercontent.com/49426644/163705446-6f47a80d-0daa-41d4-be53-f4b2eaf44907.png)

This is what I mean , and I am trying to add Microsoft Yahei font in this project , but I can't execute **"meson build"** correctly when I finished add font.

I'll be appreciate ,if you can you can check my another issue and provide some help.(●'◡'●)

**Comment by 18271211** [comment]
for my self, just copy en-us language file into hans to pass this bug...

**Comment by nodirtychinksallowed** [comment]
> > Some Chinese character are not displayed correctly, they are vacant. In my experience this is not a translation problem, this should be a lack of corresponding fonts ![image](https://user-images.githubusercontent.com/49426644/163705446-6f47a80d-0daa-41d4-be53-f4b2eaf44907.png)
> 
> This is what I mean , and I am trying to add Microsoft Yahei font in this project , but I can't execute **"meson build"** correctly when I finished adding font.
> 
> I'll be appreciate ,if you can check my another issue and provide some help.(●'◡'●)

stfu you dirty chink, go spread covid somewhere else. 

dog eating faggots

**Comment by zmk5566** [comment]
> > Some Chinese character are not displayed correctly, they are vacant. In my experience this is not a translation problem, this should be a lack of corresponding fonts ![image](https://user-images.githubusercontent.com/49426644/163705446-6f47a80d-0daa-41d4-be53-f4b2eaf44907.png)
> 
> This is what I mean , and I am trying to add Microsoft Yahei font in this project , but I can't execute **"meson build"** correctly when I finished adding font.
> 
> I'll be appreciate ,if you can check my another issue and provide some help.(●'◡'●)

Thing is, I am even sure this is caused by font issue. 

I have tested the font embeded in the ./resources/font folder, install the font on ubuntu and here is the font test result:
![screen-shot](https://user-images.githubusercontent.com/98451647/182750260-4cffea66-1ab1-4362-a541-06dfc92a41f3.png)

So either:

1. The font in the resource folder is not used atm , or 
2. some other kinda problem

**Comment by zmk5566** [comment]
As a follow up, I suspect it might be an encoding issue. To be more specific, something to do with CJK issue that is why some of the characters are missing but some of them are able to display. The reference is here. I ll try to start a build myself to see how it goes.

**Comment by CaiMiao** [comment]
@XITRIX this is because you did not load chinese shared font in your [codes](https://github.com/XITRIX/borealis/blob/main/library/lib/platforms/switch/switch_font.cpp).

i have wrote a solution of legacy borelis [here](https://github.com/CaiMiao/borealis/commit/6691a96901e4bb9abd12022f04035a6480a868d8) but did not have time look into new one as i aready using legacy. you can integrate a similar solution but i would suggest you just copy most of my code.

**Comment by CaiMiao** [comment]
I made a build to add shared font support.
[Moonlight-Switch.zip](https://github.com/XITRIX/Moonlight-Switch/files/9285695/Moonlight-Switch.zip)

**Note:** loading additional shared font consumes a few RAM, which may cause potential performance impact. if you are okay with that, just cherry-pick my commit with commenting [line out from 43](https://github.com/natinusala/borealis/blob/51bbeccd5659bf9b40943edf6c7bc37455b2c155/library/lib/platforms/switch/switch_font.cpp#L43) to 50 (consume less RAM).

if you concern about those RAM, i will suggest delete the chinese translation, or use this malformed main.json (for tofus use Japanese Kanji instead) for both Hans and Hant.
[main.json.zip](https://github.com/XITRIX/Moonlight-Switch/files/9285694/main.json.zip)

**Comment by XITRIX** [comment]
I think it was resolved long time ago, if not, please, reopen this issue
