### ISSUE TITLE
ERROR:Non-existent build file 'extern/borealis/library/meson.build'

### ISSUE THREAD

**Issue by momikiii** [XITRIX/Moonlight-Switch#64]
**Hi,M1TRIX**

**I'm trying to rebuild your project, but I am confused by this error   o(TヘTo)**

**Could you help me to fix it ?**

**Thx a lot !**

**This error occured after I execute "meson build"**

**Here is my meson-log.txt**

Build started at 2022-04-17T05:31:05.301067
Main binary: C:\Users\momiki\AppData\Local\Programs\Python\Python310\python.exe
Build Options: 
Python system: Windows
The Meson build system
Version: 0.62.0
Source dir: C:\Users\momiki\Desktop\Moonlight-Switch-0.11
Build dir: C:\Users\momiki\Desktop\Moonlight-Switch-0.11\build
Build type: native build
Project name: moonlight
Project version: 1.0.0
Sanity testing C compiler: gcc
Is cross compiler: False.
Sanity check compiler command line: gcc sanitycheckc.c -o sanitycheckc.exe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: C:\Users\momiki\Desktop\Moonlight-Switch-0.11\build\meson-private\sanitycheckc.exe
C compiler for the host machine: gcc (gcc 8.1.0 "gcc (x86_64-posix-sjlj-rev0, Built by MinGW-W64 project) 8.1.0")
C linker for the host machine: gcc ld.bfd 2.30
Sanity testing C++ compiler: c++
Is cross compiler: False.
Sanity check compiler command line: c++ sanitycheckcpp.cc -o sanitycheckcpp.exe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: C:\Users\momiki\Desktop\Moonlight-Switch-0.11\build\meson-private\sanitycheckcpp.exe
C++ compiler for the host machine: c++ (gcc 8.1.0 "c++ (x86_64-posix-sjlj-rev0, Built by MinGW-W64 project) 8.1.0")
C++ linker for the host machine: c++ ld.bfd 2.30
Sanity testing C compiler: gcc
Is cross compiler: False.
Sanity check compiler command line: gcc sanitycheckc.c -o sanitycheckc.exe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: C:\Users\momiki\Desktop\Moonlight-Switch-0.11\build\meson-private\sanitycheckc.exe
C compiler for the build machine: gcc (gcc 8.1.0 "gcc (x86_64-posix-sjlj-rev0, Built by MinGW-W64 project) 8.1.0")
C linker for the build machine: gcc ld.bfd 2.30
Sanity testing C++ compiler: c++
Is cross compiler: False.
Sanity check compiler command line: c++ sanitycheckcpp.cc -o sanitycheckcpp.exe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: C:\Users\momiki\Desktop\Moonlight-Switch-0.11\build\meson-private\sanitycheckcpp.exe
C++ compiler for the build machine: c++ (gcc 8.1.0 "c++ (x86_64-posix-sjlj-rev0, Built by MinGW-W64 project) 8.1.0")
C++ linker for the build machine: c++ ld.bfd 2.30
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64

**extern\meson.build:1:0: ERROR: Non-existent build file 'extern\borealis/library\meson.build'**

**Comment by XITRIX** [comment]
Hi, as you said "try to recompile" I could suppose that you'd like to build it for Switch, if so, you don't need meson at all. You should try [this part of manual](https://github.com/XITRIX/Moonlight-Switch#switch).
If I'm wrong and you try to build it for PC, I was not updated meson file for a long time, so it could be broken right now, but also there could be a problem with Windows build, cause I'm using macOS for development. Once I've successfully build it for Windows using MinGW, but it broke linux build, so I could revert that changes

**Comment by XITRIX** [comment]
Build system was completely reworked in v1.0, not relevant anymore
