### ISSUE TITLE
Essential libs for building

### ISSUE THREAD

**Issue by CaiMiao** [XITRIX/Moonlight-Switch#68]
totally not mentioned in readme

```sh
# for borealis
dkp-pacman -S switch-glfw switch-mesa switch-glm
# for this repo
dkp-pacman -S switch-sdl2 switch-opusfile switch-curl switch-ffmpeg switch-libexpat switch-jansson switch-glad switch-libvpx
```

btw: 
missing colon
https://github.com/XITRIX/Moonlight-Switch/blob/2a2ff3e345eeb050a0b264ab184a0317ce9015c6/resources/i18n/zh-Hant/main.json#L18

**Comment by XITRIX** [comment]
Thanks. Added all that packages into readme.
