### ISSUE TITLE
Does installing Citrix cause a ban from Nintendo?

### ISSUE THREAD

**Issue by Cageman1984** [XITRIX/Moonlight-Switch#73]
Hi! Maybe I'm asking this question in the wrong place. Redirect me if necessary.

 I am using moonlight on a raspberry pi, and i'm more than impressed. It works perfectly!

So now I want to install it on the switch (oled edition) for my kids. Seems the perfect device for it. But before I start fiddling around, I want to check the following.

For as far as I can see from the install instructions on GitHub, this seems pretty easy, without having to use custom firmware or even the homebrew store! But does installing xitrix cause any bans from Nintendo? Is it 'allowed'?. Hate to break the toys for the kids...

**Comment by Cageman1984** [comment]
Sorry, seem to have made a wrond assumption. Xitrix **does** require cfw. Sorry to bother.

**Comment by XITRIX** [comment]
Xitrix is my nickname, but you are correct, it's impossible to use moonlight homebrew without cfw :)

**Comment by Cageman1984** [comment]
Ow... Made so many mistakes in my quick search! Thanks for replying though :)
