### ISSUE TITLE
Once bitrate is changed from 10mbps, it would get "bad connection"

### ISSUE THREAD

**Issue by rakaki** [XITRIX/Moonlight-Switch#74]
If use the default bitrate of 10mbps ,streaming is perfect.
I want to know if this is my problem. Using 5GHz WFi.

**Comment by maxwellhibbert** [comment]
Same here. It’s not an issue when handheld, but when docked at 1080p it needs a higher rate.
Would using wired Ethernet allow a higher rate while docked..?

**Comment by maxwellhibbert** [comment]
I’ve got the switch overclocked when docked. Any bitrate higher than 10 still kills it though. I’m hoping a wired Ethernet adapter might allow me to put it up a bit without issues…

**Comment by maxwellhibbert** [comment]
Nope. I just found my ethernet adapter and tried it (with CPU overclock). Anything over 10Mbps still doesn't work well.

**Comment by jakefever191** [comment]
> Nope. I just found my ethernet adapter and tried it (with CPU overclock). Anything over 10Mbps still doesn't work well.

yeah i would say if you have a v1 boot into android you can get a way higher bit rate and rez due to it using the full cpu and gpu 
if you have a v2,oled or lite you will have to wait for android support  personally i don't want different os just to steam better

**Comment by Nazgile94** [comment]
if you have oled or v2 - use L4T - moonlight runs fine, gpu accelerated -- android is still missing there

**Comment by kevzz01** [comment]
> "Bad connection" is universal issue text which could appear in several conditions:
> 1080p - without CPU overclocking stream in 1080p could not decode in runtime in 60fps and because of frame drops it shows "Bad connection" error
> Bitrate more than 10mbps could cause that error, cause build into Switch WiFi module is absolute garbage, it is bad as hell and it could not transfer more than 10mbps, so this error appeeres

I’m getting bad connection on my OLED switch. Could it be because I’m streaming with native resolution on my PC which is 1440p? Would it help if I change the resolution to 720p or at least 1080p? My pc is wires and moonlight is working just fine with my other switch v1 on android.

**Comment by kevzz01** [comment]
> if you have oled or v2 - use L4T - moonlight runs fine, gpu accelerated -- android is still missing there

Can you dual boot with it just like the android with v1 switch?

**Comment by jedinjapan** [comment]
Issue still persists. v1, anything over 10mbps causes massive lag regardless of resolution chosen. Unfortunate given the 1080p upper limit, the higher bitrate encoding would be nice for high action titles.

**Comment by XITRIX** [comment]
Should not be an issue anymore, as HW acceleration was implemented

**Comment by xenophobentx** [comment]
> Should not be an issue anymore, as HW acceleration was implemented

Actually,  when i use high bitrate with HW acceleration it is still lagging for example 20mpbs with 1080p in handheld it is lagging. But if i overclock my CPU  it is working flawlessly. Also interesting if you overclock you will get lower decoding latency times even with HW acceleration.

**Comment by XITRIX** [comment]
I think it's because of OpenGL overhead that utilise CPU also, but I'm not sure
