### ISSUE TITLE
moonlight-switch often crashes with errors

### ISSUE THREAD

**Issue by Jerning** [XITRIX/Moonlight-Switch#75]
1. Open moonlight
2. Press the home button (it will crash)
3. Network freezes

All of the above crashes randomly

error code:2144-0001(0x290)
program: 0100000000001000
firmware: 15.0.1 atmosphere 1.4.0

**Comment by XITRIX** [comment]
Are you running app via Applet mode?

**Comment by Jerning** [comment]
oh, think you!
I learned about Applet mode later. After using Applet mode, it is now normal.

**Comment by XITRIX** [comment]
You should run app in Full RAM mode, instead of Applet mode, app crashes cause it's not enough RAM for it to work properly. Glad it helped
