### ISSUE TITLE
Docked and Handheld resolution settings

### ISSUE THREAD

**Issue by maxwellhibbert** [XITRIX/Moonlight-Switch#79]
It would be sweet if we could set a resolution for both docked and handheld modes. I'd say bitrate as well, but the switch can't seem to go past 10, so probably not important :)

Also, I really appreciate your work on this project. It works very well and all the features you've added over time have made it awesome to use.

**Comment by XITRIX** [comment]
Hmm... It could be a good idea! :)

**Comment by XITRIX** [comment]
Implemented as "Native" resolution option, it will use current screen resolution to connect to server, different bitrate options are not planning to implement
