### ISSUE TITLE
Minor Issue "DRM protected contect" no message pop-up

### ISSUE THREAD

**Issue by andyktaylor** [XITRIX/Moonlight-Switch#8]
When I try to run a game and there is DRM protected content on my PC, the client crashes without any message, and the launcher shows the game is running (and looking at my PC that is the case). 

If I do the same thing, on say, my Nvidia Shield, I get a warning pop-up saying "unable to stream due to DRM portected content"

It's not really a biggie, but would be nice to get that alert, rather than just being dumped back to the launcher.

**Comment by linhtranvu** [comment]
too rare issue, even this is not issue but personal setting, so I think dev could ignore this

**Comment by XITRIX** [comment]
Ok, I will close it until any real case will described.

**Comment by yeet-dot-org** [comment]
> Hi, thanks for report, never even thought there are DRM protected content that could not be launched by Nvidia Shield...
> 
> Could you tell me an example of such game, may be I have one, and will try to catch that error? Basically, all error messages come from Moonlight core, so may be I'll redirect that issue there.

i have the same issue with prime video, I kind of do need it as i like to be able to watch a show while playing a game.
