### ISSUE TITLE
Error issue on Korean test ver.

### ISSUE THREAD

**Issue by DDinghoya** [XITRIX/Moonlight-Switch#81]
Dear,

The reason is unclear, but The intermittent error is shown in the picture below;

![error](https://user-images.githubusercontent.com/19677686/206458112-b2973a61-80fd-4c8c-8253-80bbfea66aa1.png)

Are there any reports of the same problem as mine for other language?

**Comment by DDinghoya** [comment]
> Have you launched app via title redirection or just by "Photos app"?

Yes, I launched it on Photos app.

**Comment by XITRIX** [comment]
That's the problem, it's an Applet Mode, with low RAM access. You should run it via title redirection by launching any title on your Switch holding R button

**Comment by DDinghoya** [comment]
> That's the problem, it's an Applet Mode with low RAM access. You should run it via title redirection by launching any title on your Switch while holding R button

Thank you for your strong support!!! I will follow your instructions. :)

**Comment by XITRIX** [comment]
So I'll close this issue, if you'll have any questions be free to reopen it ;)
