### ISSUE TITLE
Touch emulate as moonlight-nx

### ISSUE THREAD

**Issue by maytinhdibo** [XITRIX/Moonlight-Switch#83]
In Moonlight-NX, we can use the touch screen on Switch as touchscreen on Windows. With it, we will use touch screen con Citra on PC.
![image](https://user-images.githubusercontent.com/6669725/207542154-80f00be5-f699-4b38-92ef-67e57e9c2f5e.png)

**Comment by XITRIX** [comment]
Hmm, nice point, I'll try to figure it out

**Comment by Skyyblaze** [comment]
Sorry to bug but is this still being looked into? I had both Moonlight NX and Moonlight Switch on my system for exactly this reason as I found Switch generally be better but NX was useful for the touch-screen feature. As of the latest Nvidia GameReady driver NX stopped working though :(

**Comment by XITRIX** [comment]
Hi, I'm not actively maintain current version of Moonlight-Switch, cause I'm creating my own UI framework at this moment. I think when I'm done I'll rewrite entire Moonlight-Switch from scratch, so I don't want to spend extra time to the stuff I'll rewrite anyway. If I'll have some spare time, I'll try to implement this, but I could not promise it, sorry.

**Comment by XITRIX** [comment]
Ok, nevermind, I've found some time to implement this. I did not tested it too much, but seems like it's working.

@Skyyblaze, check out [this build](https://github.com/XITRIX/Moonlight-Switch/actions/runs/4365116610) and say if works fine or it need some tuning.

**Comment by Skyyblaze** [comment]
Thank you so much, also for your future work! I'm waiting for the build to finish and will then report back :)

**Comment by Skyyblaze** [comment]
@XITRIX Hmm it seems to work semi-correctly. It does partially work like it should but the mouse-position seems to be relative to where the mouse currently is on the screen instead of being absolutely where I touch which leads to lots of weird inputs :(

**Comment by XITRIX** [comment]
ok, I'll try to check what's going wrong

**Comment by Skyyblaze** [comment]
> Ok, I'll try to check what's going wrong, I think I messed up with an order of mouse position change and button click

Thank you! Tag me when you have a new build, I'll gladly test again :)

**Comment by renA21** [comment]
[Native touch support](https://github.com/LizardByte/Sunshine/pull/1483) is available on Sunshine nightly. It’ll be better to use that rather than emulating it with the mouse.

**Comment by renA21** [comment]
It’s available in core since https://github.com/moonlight-stream/moonlight-common-c/commit/4a48024dc825a19a3c5d27ca53dbd025b93ead45

**Comment by GrayXu** [comment]
this feature will be very useful in many touch-based games, thank you for your contribution!

**Comment by XITRIX** [comment]
Implemented in v1.0
