### ISSUE TITLE
Allow more fps options

### ISSUE THREAD

**Issue by maytinhdibo** [XITRIX/Moonlight-Switch#84]
Bitrate at 15 have more great quality. However I just have smooth experience with 30fps. When downgrade bit rate to 10, so I can play 60fps. 

I hope the team can allow 40fps as new option like steam deck.

**Comment by mrwiwi** [comment]
And 120 fps to lower latency (yes i know, on a 60hz screen)

**Comment by XITRIX** [comment]
I'm not sure that it's what possible to do with Moonlight-Core, I'll check it

**Comment by maytinhdibo** [comment]
> I'm not sure that it's what possible to do with Moonlight-Core, I'll check it

Core support it

**Comment by XITRIX** [comment]
Added 120 fps option

Released in v1.1.0

**Comment by XITRIX** [comment]
Probably need to add 40 fps as well

**Comment by Wontell** [comment]
> Probably need to add 40 fps as well

Please add 40, you have 45 but it doesn't make sense, its 60hz screen so there should be:
20, 30, 40, 60 and 120

**Comment by XITRIX** [comment]
https://github.com/XITRIX/Moonlight-Switch/actions/runs/11751360314
