### ISSUE TITLE
Crashing the entire atmosphere upon opening moonlight. Starting it in Title Redirection crashes hekate too.

### ISSUE THREAD

**Issue by TNitroo** [XITRIX/Moonlight-Switch#86]
Hello there.
So, I was really happy about the fact, that you've made this app to the switch, because this is just what I needed. But, the issue is, that at first, it was fine, going well, I was able to play some on it. After that, I've closed the app, since I wanted to play some other games. After that, I went back to it, to test this app some more, so I know what to expect, how well it runs different games and such. This time, I was trying to run it in Title Redirection, like you've mentioned in the installing part (I reinstalled it) and as I was opening it, it crashed my atmosphere and even hekate, that it couldn't boot me into atmosphere again and had to use my payload to load hekate. After that, I did manage to use it, but only in normal mode, not Title Redirection. It still crashes my switch entirely, so I didn't want to try it again. And now, after some gameplay (I've played for like half an hour) it crashed my switch to reboot, but this time, it only crashed atmosphere and it was able to reload into it. But now, every time I try to open it, it immediately crashes and gives me the fatal error. (crash reports included) I don't know what could cause this, since I have the newest version of everything. (Hekate, Atmosphere and moonlight too). Hope we can find a solution to this and for people facing the same issue later as I do.
[01673982625_0100ff500e34a000.log](https://github.com/XITRIX/Moonlight-Switch/files/10439459/01673982625_0100ff500e34a000.log)
[01673982633_010000000000100d.log](https://github.com/XITRIX/Moonlight-Switch/files/10439460/01673982633_010000000000100d.log)
[01673982953_010000000000100d.log](https://github.com/XITRIX/Moonlight-Switch/files/10439461/01673982953_010000000000100d.log)
[01673987115_010000000000100d.log](https://github.com/XITRIX/Moonlight-Switch/files/10439462/01673987115_010000000000100d.log)
[01673989082_010000000000100d.log](https://github.com/XITRIX/Moonlight-Switch/files/10439463/01673989082_010000000000100d.log)
[01673989156_010000000000100d.log](https://github.com/XITRIX/Moonlight-Switch/files/10439464/01673989156_010000000000100d.log)

**Comment by TNitroo** [comment]
Hey there. Some update here. So, the thing is, that its literally inconsistent now, after further trying it to recreate the issue. If I was playing something beforehand and close the game, wait a few seconds and then open moonlight, it crashes the entire system and needs a payload to boot again, but if I just open it and close it, it only crashes atmosphere. I will try a few things, like deleting everything that moonlight has created on my switch and installing it via the homebrew appstore. Hope it fixes the things, because I really want to use this app without any issues and use it to its fullest.
[01674034920_010000000000100d.log](https://github.com/XITRIX/Moonlight-Switch/files/10444480/01674034920_010000000000100d.log)
[01674035067_010000000000100d.log](https://github.com/XITRIX/Moonlight-Switch/files/10444481/01674035067_010000000000100d.log)
[01674035813_010000000000100d.log](https://github.com/XITRIX/Moonlight-Switch/files/10444482/01674035813_010000000000100d.log)

**Comment by TNitroo** [comment]
Third update.
So, I downloaded the older version, 0.12.0 and it is a lot more stable and I couldn't get it to crash just by using it like ppl would normally use an app. The only way I was able to crash it, was by first opening it in title redirection and then opening it again in applet mode, but the reason is obvious, why it crashed there.

**Comment by XITRIX** [comment]
Hi, thanks for your detailed report, everything you described sounds crazy, I've never get an entire Atmosphere crashed while using my app (only applet mode have done this to me). You've mentioned that you've "reinstall" app to use Title Redirection, what do you mean by that? Title redirection is when you hold 'R' button while launching any game, you don't need to "reinstall" something, so maybe you've done wrong on that step?

P.S. I'm also using latest Atmosphere so there should not be any problem

**Comment by TNitroo** [comment]
What I meant by that was, that I just reinstalled moonlight completely to have a fresh files, so there could be no issues at all.
Btw, for some reason, it did these stuffs a lot less since, but I still get the same stuff some times. Still not sure what could cause this.

**Comment by XITRIX** [comment]
https://github.com/XITRIX/Moonlight-Switch/actions

**Comment by mathiasschuetz** [comment]
I also just started it the first time and it crashed after some seconds my whole atmosphere (latest HATS pack from https://github.com/sthetix/HATS - clean install). I needed to restart again.

**Comment by XITRIX** [comment]
Should be fixed in v1.0
