### ISSUE TITLE
Frequent occurrence: ERROR 2168-0002

### ISSUE THREAD

**Issue by javazwz123** [XITRIX/Moonlight-Switch#88]
Atmospheric System 15.0.1 AMS1.4, Nvidia's driver is also updated to the latest, and then the streaming can be successful, but the error code shown in the figure often appears
![WechatIMG375](https://user-images.githubusercontent.com/16428277/217125799-b9a0ea79-a8d1-45ab-85a7-d4e9e227fad1.jpeg)

**Comment by XITRIX** [comment]
Are you running HB Launcher with title redirection (holding R key while launching any game) or via Album app?

**Comment by javazwz123** [comment]
> 

Album app

**Comment by XITRIX** [comment]
It is not allowed to run this app via album app, Moonlight requires more RAM than applet mode (album app) could provide, so Atmosphere crashes, you should run it with title redirection

**Comment by javazwz123** [comment]
> It is not allowed to run this app via album app, Moonlight requires more RAM than applet mode (album app) could provide, so Atmosphere crashes. You should run it with title redirection

thank u
