### ISSUE TITLE
[enhancement] Stream game shortcuts

### ISSUE THREAD

**Issue by vos6434** [XITRIX/Moonlight-Switch#9]
Could you make it possible to create a game shortcut on the switch home screen or in the homebrew menu?

**Comment by XITRIX** [comment]
Hi, I think it's a cool idea, but I'm not sure about how to do it well. Right now I think I could add a "favorite" button to put favorite apps on top of the list. Later I could add a separate tab in main menu with favorite games.

I'm not sure about homescreen shortcuts, but you could create a nro2nsp forwarder by your self.

**Comment by vos6434** [comment]
yeah i could use the nro2nsp for the nsp. Is it possible for the app to generate an nro game shortcut?

**Comment by XITRIX** [comment]
Right now, no. I'll think about possibility of doing that.

**Comment by XITRIX** [comment]
I'm not sure that it is possible to do, but I've added favorites list. It should also improve stream startup speed. It is already available in [v0.9](https://github.com/XITRIX/Moonlight-Switch/releases/tag/v0.9)
