### ISSUE TITLE
Last build failed 

### ISSUE THREAD

**Issue by thefiredragon** [XITRIX/Moonlight-Switch#90]
Dear
Thanks for this nice project, I really love moonlight on my nx.
Last days you updated the moonlight common sources, could you fix the last build issue soon?

This contain some useful fixes for sunlight host client,
Beat regards
Dan

**Comment by XITRIX** [comment]
Yes, I’ll try, but I have no idea why it stopped building, new version of libnx contains new code contributed by me to make it able to compile latest version of moonlight. May be there is some problems with building machine to update libnx to latest version.

**Comment by XITRIX** [comment]
[Moonlight-Switch.nro.zip](https://github.com/XITRIX/Moonlight-Switch/files/11184320/Moonlight-Switch.nro.zip)

Anyway I could share it here if you really need it right now ;)

**Comment by thefiredragon** [comment]
Thank you,
I was able to build with newer moonlight-common when I use enet package before  commit "Correctly support hosts with multiple possible source addresses"

Looks this changes break something or how u said libnx could be the problem

**Comment by XITRIX** [comment]
No, changes are absolutely fine. You'll be unable to compile latest commit without latest version of libnx and I think docker's image do not update it

**Comment by derfehler** [comment]
perhaps this solution will help #97
