### ISSUE TITLE
Not working with firmware 16.0.1 even with extra ram

### ISSUE THREAD

**Issue by FlameSlap** [XITRIX/Moonlight-Switch#92]
wont even boot when launched

**Comment by XITRIX** [comment]
Try to delete /switch/Moonlight-Switch folder

I have 16.0.1 on my own Switch and app is running well

**Comment by FlameSlap** [comment]
ok I will try now and edit this comment to update.

**Comment by FlameSlap** [comment]
> Try to delete /switch/Moonlight-Switch folder
> 
> I have 16.0.1 on my own Switch and app is running well


ok I will try now and edit this comment to update.

**Comment by XITRIX** [comment]
For unknown reason, sometime it could create broken certificate and app crashes trying to use it, so removing it could help.
