### ISSUE TITLE
[Feature Request] Customise port to connect to PC

### ISSUE THREAD

**Issue by Cokkie203** [XITRIX/Moonlight-Switch#93]
i have a sunshine setup with custom ports because my isp has split my ip in 4 and i have the last quarter
this feature already works in pc and android with this model
XXX.XXX.XXX.XXX:YYYYY
X being ip and Y is the port
i already tried and made the not recognized address error

**Comment by XITRIX** [comment]
Yes, IP field is only recognises the IP address, not port. May be I'll add it later

**Comment by artslay** [comment]
> Yes, IP field is only recognises the IP address, not port. May be I'll add it later

its working now?

**Comment by Cokkie203** [comment]
Nope
Not in the way I showed

**Comment by artslay** [comment]
> Nope Not in the way I showed

do you find the solution?

**Comment by Cokkie203** [comment]
No
currently not working on my switch
It is on my phone but the screen is too small

**Comment by GrayXu** [comment]
https://github.com/XITRIX/Moonlight-Switch/blob/c9162744974dd06a142c1f84f698f57f87ce4f53/app/src/libgamestream/client.cpp#L58C7-L60

It seems that the port settings are fixed here, and a simple way is to directly modify and recompile.
It looks like Moonlight should have multiple ports. I wonder how the app on the phone manually sets multiple ports?

**Comment by XITRIX** [comment]
https://github.com/XITRIX/Moonlight-Switch/actions/runs/11391388665
Finally I found some time to implement it, need some tests though

**Comment by XITRIX** [comment]
Released in v1.2.2
