### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by yangkuang22** [XITRIX/Moonlight-Switch#94]
even use HB Launcher  Random crashes, sometimes it takes several times to open, after exiting the stream, there is a high probability of not being able to reconnect, there is a high probability of crashing, and it feels like everything depends on luck

**Comment by Lamcza** [comment]
yep cant even start it on 16.1.0 atmo 1.5.5 just the software was closed generic error

**Comment by XITRIX** [comment]
Should be fixed in v1.0
