### ISSUE TITLE
[Feature request] Gyroscope amplification setting

### ISSUE THREAD

**Issue by CipherLab** [XITRIX/Moonlight-Switch#98]
It would be awesome if this version of moonlight could pass gyro data to Sunshine, now that it's starting to support it:
https://github.com/moonlight-stream/moonlight-qt/issues/960

**Comment by XITRIX** [comment]
https://github.com/moonlight-stream/moonlight-qt/commit/9af58af5e4aa536083ad62997135c1f9c03430ec

I'll left it here not to lose. If this feature is implemented on moonlight-common-c side, I think I could try to implement it later

**Comment by joshbirnholz** [comment]
I think gyro is supported now, it would be great if we can get it implemented!

**Comment by XITRIX** [comment]
[Moonlight.nro.zip](https://github.com/XITRIX/Moonlight-Switch/files/14115235/Moonlight.nro.zip)

Try to test this build, does gyro works properly?

**Comment by joshbirnholz** [comment]
> [Moonlight.nro.zip](https://github.com/XITRIX/Moonlight-Switch/files/14115235/Moonlight.nro.zip)
> 
> Try to test this build, does gyro works properly?

No, I tried this build out and gyro didn't seem to be working. I connected with Moonlight from an Android tablet and gyro worked there, but still no on Switch with that built.

**Comment by XITRIX** [comment]
Did it recognised as DS4 controller or as xBox one?

**Comment by joshbirnholz** [comment]
It gets recognized as an Xbox controller.

**Comment by XITRIX** [comment]
Change Sunshine settings to recognise it as DS4, xBox one do not support SixAxis

**Comment by joshbirnholz** [comment]
I actually originally had Sunshine set to recognize it as DS4, but the gyro still wasn't working.

Setting it to Auto made it get recognized as an Xbox controller. My android tablet, which does have motion controls working, gets recognized as DS4 when Sunshine is set to auto.

**Comment by jackazz86** [comment]
That's actually working! Although gyro sensitivity is a bit low (can be tweaked inside Steam options).

- Sunshine v0.21.0
- Latest Client Uploaded above in this thread

Thank you very much for all the amazing work! This final update is pure magic.

**Comment by XITRIX** [comment]
Released in v1.0

**Comment by joshbirnholz** [comment]
The sensitivity for me is more than just a bit low. Even if I wildly swing my controller/console, only a slight movement is picked up. Can the sensitivity be increased, or be made configurable? We shouldn't need to have to increase sensitivity through Steam, and it's unusable right now with how low it is.

**Comment by XITRIX** [comment]
I'm using raw values from Switch sensors, I'll take a look about amplification setting

**Comment by IISAKNIFE** [comment]
Any update on a way to amplify gyro sensitivity?

**Comment by XITRIX** [comment]
Not yet, sorry, unfortunately don't have enough time to sit and make it ...

**Comment by XITRIX** [comment]
This issue will be handled in #149
